### ISSUE TITLE
dynamic module does not define init function?

### ISSUE THREAD

**Issue by talenz** [wondervictor/WiderFace-Evaluation#1]
Traceback (most recent call last):
  File "evaluation.py", line 14, in <module>
    from bbox import bbox_overlaps
ImportError: dynamic module does not define init function (initbbox)

**Comment by wondervictor** [comment]
Have you run the setup?
````
python3 setup.py build_ext --inplace
````

**Comment by talenz** [comment]
> Have you run the setup?
> 
> ```
> python3 setup.py build_ext --inplace
> ```

yes, it generated the file "bbox.so"

**Comment by talenz** [comment]
> Have you run the setup?
> 
> ```
> python3 setup.py build_ext --inplace
> ```


Warning: Extension name 'bbox' does not match fully qualified name 'box_overlaps' of 'box_overlaps.pyx'
running build_ext
building 'bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c box_overlaps.c -o build/temp.linux-x86_64-2.7/box_overlaps.o
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from box_overlaps.c:494:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/box_overlaps.o -L/usr/lib64 -lpython2.7 -o /aiml/t00475017/WiderFace-Evaluation/bbox.so

**Comment by wondervictor** [comment]
It seems that the cython module has been compiled successfully.
Maybe you can follow the suggestions from https://stackoverflow.com/questions/8024805/cython-compiled-c-extension-importerror-dynamic-module-does-not-define-init-fu/13976504#13976504

**Comment by wondervictor** [comment]
Have you solved this problem? @talenz

**Comment by talenz** [comment]
> Have you solved this problem? @talenz

It worked after I modified your library name, but the results (mAP in your code) are always nearly 0.

**Comment by wondervictor** [comment]
I've compared the results from Matlab before pushing. Can you provide part of your results? and I'll check what's wrong

**Comment by talenz** [comment]
> I've compared the results from Matlab before pushing. Can you provide part of your results? and I'll check what's wrong

My results work fine in MATLAB. My python version is 2.7.5, does your code work in python 2?

**Comment by wondervictor** [comment]
Oh, sorry, I haven't tested my code on Python2.7. My evaluation code is inherited from the official MATLAB including the format of the results.

**Comment by wondervictor** [comment]
Maybe, some division `/`  operators result in the wrong output. Default `/` is quite different in Python2 (integer) and Python3(float/double).

**Comment by wondervictor** [comment]
Or you can add this line in `evaluation.py`
```
from __future__ import division
```

**Comment by talenz** [comment]
> Or you can add this line in `evaluation.py`
> 
> ```
> from __future__ import division
> ```

It worked, thank you.

**Comment by wondervictor** [comment]
Okay

**Comment by SURABHI-GUPTA** [comment]
I am still getting nearly zero values
