### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 16: invalid continuation byte

### ISSUE THREAD

**Issue by luyao777** [wondervictor/WiderFace-Evaluation#4]
Hi, I got this problem
> Reading Predictions :   0%|                                                                                                                                                                                            | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
  File "evaluation.py", line 280, in <module>
    evaluation(args.pred, args.gt)
  File "evaluation.py", line 217, in evaluation
    pred = get_preds(pred)
  File "evaluation.py", line 104, in get_preds
    imgname, _boxes = read_pred_file(os.path.join(event_dir, imgtxt))
  File "evaluation.py", line 85, in read_pred_file
    lines = f.readlines()
  File "/home/luyao/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 16: invalid continuation byte

**Comment by luyao777** [comment]
Oh, there is a swap file in the predict folder!

**Comment by Thishaw21** [comment]
how to fix this error, i have the same problem
